### ISSUE TITLE
Doesn't work with same database relationships

### ISSUE THREAD

**Issue by alexsmedile** [stevedsun/notion-graph-view#26]
I have set up a bunch of relations with the same database. So a page might link to another page on the same database.

Graph View doesn't seem to display these relations.

I have just a single blob in the centre of the main database. No other link or channel has been created even tho I have many.

Also, it gives error: file graph_out.html not found, even tho the export has been completed successfully on my desktop.

And, random elements in the graph view will just collapse onto each other, overlapping each other's.

**Comment by patzm** [comment]
I have just pointed the tool to a database with relationships to itself (asymmetric relationship) and it worked. Both in-page links and database links worked. Maybe try again 🙂, it has been ~6 months since you tried. Maybe it was fixed / implemented but this issue forgotten to be closed.
<img src="https://github.com/user-attachments/assets/5607d5c2-a8fa-439c-a554-6e890ad7a5a4" width="400px">

**Comment by stevedsun** [comment]
thanks for feedback!
