### ISSUE TITLE
Opening the selected page in the graph on Notion

### ISSUE THREAD

**Issue by fatihemree** [stevedsun/notion-graph-view#28]
Hello, I really liked this project you developed on Notion and enjoyed reviewing my notes on Notion. However, opening the selected page from the graph on Notion would greatly enhance the experience. Do you have any plans for this, or if it’s already available, could you please inform me? :)

**Comment by stevedsun** [comment]
Hi @fatihemree I have added a page link when hovering on a node of graph.
Due to the dependency package missing node URL property, this is a work around and I will change to a better implementation afterwards.

![image](https://github.com/stevedsun/notion-graph-view/assets/5465534/ab42454d-4e16-491c-bdf8-32d1e96d7d6d)

**Comment by fatihemree** [comment]
Thank you, I can’t wait to try it. 🙏🏻
