### ISSUE TITLE
Question: more link support?

### ISSUE THREAD

**Issue by Bobronium** [stevedsun/notion-graph-view#5]
Hello, @stevedsun! I've just stumbled across this project, great stuff!

I was wondering, are these link types on the roadmap, or not supported because some kind of limitation?

- embed
- callout
- quote
- column
- column_list
- synced_block
- link_to_page
- table_row

I saw that lib was updated from using client to using SDK, and I can imagine these types of links weren't possible to track using `token_v2`. 

Is it still impossible to track with data from an SDK or now it can be implemented? If it's possible, I would be happy to collaborate!

**Comment by stevedsun** [comment]
Hi @Bobronium , due to Notion API limitation, following types could not be parsed:
- embed
- synced_block
- link_to_page (Notion return "unsupport" type when I debug API response.)

But other types are supported and in my dev plan, welcome to contribute code.

The old project code using `token_v2` to parse webpage, could not keep up with Notion official updates, therefore I updated it with Notion-API instead.

Now this project has some issues, like slow speed and parsing too many useless blocks. I am going to fix them as soon as possible.

**Comment by Bobronium** [comment]
Thanks for response! 

> link_to_page (Notion return "unsupport" type when I debug API response.)

Could you give an example request, so I could continue from where you stopped?

It seems that Notion API support [Link to Page block type](https://developers.notion.com/changelog/synced-block-link-to-page-and-template-block-types-are-now-supported-in-the-api#link-to-page-block-type). Maybe there's a bug in the API?

**Comment by stevedsun** [comment]
Sorry I debug it by my own Notion account, so I cannot share it with you.
You can reproduce it by:
1. create a page (say A), add a link_to_page block in A
2. call notion api to retrieve A's children: GET https://api.notion.com/v1/blocks/{Block_A_ID}/children
3. You may find an "unsupport" type in children list

You can also refer to [Notion API Reference](https://developers.notion.com/reference/get-block-children)
